/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'gst' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'deliveryFee' : bigint,
  'grandTotal' : bigint,
  'timestamp' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'selectedPriceLabel' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface PlaceOrderRequest {
  'gst' : bigint,
  'customerName' : string,
  'deliveryAddress' : string,
  'deliveryFee' : bigint,
  'grandTotal' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface _SERVICE {
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];