/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'selectedPriceLabel' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'gst' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'deliveryFee' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const PlaceOrderRequest = IDL.Record({
  'gst' : IDL.Nat,
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'deliveryFee' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'selectedPriceLabel' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'gst' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'deliveryFee' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const PlaceOrderRequest = IDL.Record({
    'gst' : IDL.Nat,
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'deliveryFee' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  
  return IDL.Service({
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };